import Foundation

/* Problem 2 --
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

var sum = 0
var previousFibonacciNumber = 1
var currentFibonacciNumber = 1
while currentFibonacciNumber < 4_000_000 {
    let nextFibonacciNumber = previousFibonacciNumber + currentFibonacciNumber
    previousFibonacciNumber = currentFibonacciNumber
    currentFibonacciNumber = nextFibonacciNumber
    if currentFibonacciNumber.isEven() {
        sum += currentFibonacciNumber
    }
}

print(sum)

sum == 4613732
// CORRECT ANSWER: 4613732